# Setup

In [1]:
# enable to reimport modules
%load_ext autoreload
%autoreload 2

In [2]:
import warnings

import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_columns = 999

In [3]:
warnings.filterwarnings('ignore')

# Usable Features List

In [4]:
from scripts.feature import FeatureFactory
for lst in FeatureFactory().feature_list():
    print(f'"{lst}"')

"MoleculeCount"
"MoleculeDistanceStatistics"
"Atom0Count"
"Atom1Count"
"Atom"

# Experiment

In [19]:
from scripts.experiment import Experiment
ex = Experiment()
# ex = Experiment(dataset, X_train,  y_train, X_test)
y_pred = ex.run(nrows=None)
dataset = ex.dataset_
X_train = ex.X_train_
y_train = ex.y_train_
X_test = ex.X_test_

Target: fc

100%|██████████| 4/4 [00:20<00:00,  5.36s/it]
100%|██████████| 4/4 [00:10<00:00,  2.83s/it]

not found best parameters
Score: 2.977014868958579

In [20]:
dataset.train.head()

                                            id  type  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0              0  1JHC
                              2              1  2JHH
                              3              2  2JHH
                              4              3  2JHH
                 2            0              4  1JHC

                                            scalar_coupling_constant  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                              84.8076
                              2                             -11.2570
                              3                             -11.2548
                              4                             -11.2543
                 2            0                              84.8074

                                            atom_index_x atom_0       x_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                        1      H  0.002150
                              2                        1      H  0.002150
                              3                        1      H  0.002150
                              4                        1      H  0.002150
                 2            0                        2      H  1.011731

                                                 y_0       z_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0            -0.006031  0.001976
                              2            -0.006031  0.001976
                              3            -0.006031  0.001976
                              4            -0.006031  0.001976
                 2            0             1.463751  0.000277

                                            electronegativity_x  radius_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                             2.2      0.43
                              2                             2.2      0.43
                              3                             2.2      0.43
                              4                             2.2      0.43
                 2            0                             2.2      0.43

                                            n_bonds_x  bond_lengths_mean_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                     1             1.091953
                              2                     1             1.091953
                              3                     1             1.091953
                              4                     1             1.091953
                 2            0                     1             1.091952

                                            bond_lengths_std_x  atom_index_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                            0.0             0
                              2                            0.0             2
                              3                            0.0             3
                              4                            0.0             4
                 2            0                            0.0             0

                                           atom_1       x_1       y_1  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 C -0.012698  1.085804
                              2                 H  1.011731  1.463751
                              3                 H -0.540815  1.447527
                              4                 H -0.523814  1.437933
                 2            0                 C -0.012698  1.085804

                                                 z_1  electronegativity_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.008001                 2.55
                              2             0.000277                 2.20
                              3            -0.876644                 2.20
                              4             0.906397                 2.20
                 2            0             0.008001                 2.55

                                            radius_y  n_bonds_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 0.82          4
                              2                 0.43          1
                              3                 0.43          1
                              4                 0.43          1
                 2            0                 0.82          4

                                            bond_lengths_mean_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                        1.091950
                              2                        1.091952
                              3                        1.091946
                              4                        1.091948
                 2            0                        1.091950

                                            bond_lengths_std_y      dist  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                       0.000003  1.091953
                              2                       0.000000  1.783120
                              3                       0.000000  1.783147
                              4                       0.000000  1.783157
                 2            0                       0.000003  1.091952

                                              dist_x    dist_y    dist_z  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.000220  1.192105  0.000036
                              2             1.019253  2.160261  0.000003
                              3             0.294812  2.112831  0.771973
                              4             0.276638  2.085032  0.817978
                 2            0             1.049455  0.142844  0.000060

                                           type_0       fc        sd      pso  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 1  83.0224  0.254579  1.25862
                              2                 2 -11.0347  0.352978  2.85839
                              3                 2 -11.0325  0.352944  2.85852
                              4                 2 -11.0319  0.352934  2.85855
                 2            0                 1  83.0222  0.254585  1.25861

                                                 dso
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.272010
                              2            -3.433600
                              3            -3.433870
                              4            -3.433930
                 2            0             0.272013

In [22]:
dataset.test.head()

                                                 id  type  atom_index_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0             4658147  2JHC             2
                              1             4658148  1JHC             2
                              3             4658149  3JHH             2
                 3            0             4658150  1JHC             3
                              1             4658151  2JHC             3

                                           atom_0       x_0  y_0  z_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                 H -1.661639  0.0  1.0
                              1                 H -1.661639  0.0  1.0
                              3                 H -1.661639  0.0  1.0
                 3            0                 H  1.661639  0.0  1.0
                              1                 H  1.661639  0.0  1.0

                                            electronegativity_x  radius_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                             2.2      0.43
                              1                             2.2      0.43
                              3                             2.2      0.43
                 3            0                             2.2      0.43
                              1                             2.2      0.43

                                            n_bonds_x  bond_lengths_mean_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                     1             1.062099
                              1                     1             1.062099
                              3                     1             1.062099
                 3            0                     1             1.062099
                              1                     1             1.062099

                                            bond_lengths_std_x  atom_index_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                            0.0             0
                              1                            0.0             1
                              3                            0.0             3
                 3            0                            0.0             0
                              1                            0.0             1

                                           atom_1       x_1  y_1  z_1  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                 C  0.599539  0.0  1.0
                              1                 C -0.599539  0.0  1.0
                              3                 H  1.661639  0.0  1.0
                 3            0                 C  0.599539  0.0  1.0
                              1                 C -0.599539  0.0  1.0

                                            electronegativity_y  radius_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                            2.55      0.82
                              1                            2.55      0.82
                              3                            2.20      0.43
                 3            0                            2.55      0.82
                              1                            2.55      0.82

                                            n_bonds_y  bond_lengths_mean_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                     2             1.130589
                              1                     2             1.130589
                              3                     1             1.062099
                 3            0                     2             1.130589
                              1                     2             1.130589

                                            bond_lengths_std_y      dist  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                        0.06849  2.261178
                              1                        0.06849  1.062099
                              3                        0.00000  3.323277
                 3            0                        0.06849  1.062099
                              1                        0.06849  2.261178

                                               dist_x  dist_y  dist_z type_0
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0              5.112926     0.0     0.0      2
                              1              1.128054     0.0     0.0      1
                              3             11.044171     0.0     0.0      3
                 3            0              1.128054     0.0     0.0      1
                              1              5.112926     0.0     0.0      2

# Show the Dataframes

In [33]:
X_train.head()

                                            id  molecule_dist_mean  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1             10            1.506668
                              2             10            1.506668
                              3             10            1.506668
                              4             10            1.506668
                 2            1             10            1.506668

                                            molecule_dist_min  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                      1.091946
                              2                      1.091946
                              3                      1.091946
                              4                      1.091946
                 2            1                      1.091946

                                            molecule_dist_max  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                      1.783158
                              2                      1.783158
                              3                      1.783158
                              4                      1.783158
                 2            1                      1.783158

                                            atom_0_couples_count  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                                4
                              2                                3
                              3                                2
                              4                                1
                 2            1                                4

                                            atom_1_couples_count
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                                4
                              2                                4
                              3                                4
                              4                                4
                 2            1                                1

In [34]:
y_train.head()

                                                 fc  type
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             83.0224  1JHC
                              2            -11.0347  2JHH
                              3            -11.0325  2JHH
                              4            -11.0319  2JHH
                 2            0             83.0222  1JHC

In [35]:
X_test.head()

                                            id  molecule_dist_mean  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2              5            1.993966
                              3              5            1.993966
                 1            2              5            1.993966
                              3              5            1.993966
                 3            2              5            1.993966

                                            molecule_dist_min  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                      1.062099
                              3                      1.062099
                 1            2                      1.062099
                              3                      1.062099
                 3            2                      1.062099

                                            molecule_dist_max  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                      3.323277
                              3                      3.323277
                 1            2                      3.323277
                              3                      3.323277
                 3            2                      3.323277

                                            atom_0_couples_count  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                                3
                              3                                2
                 1            2                                3
                              3                                2
                 3            2                                3

                                            atom_1_couples_count
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                                2
                              3                                2
                 1            2                                2
                              3                                2
                 3            2                                1

In [36]:
dataset.train.head()

                                            id  type  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0              0  1JHC
                              2              1  2JHH
                              3              2  2JHH
                              4              3  2JHH
                 2            0              4  1JHC

                                            scalar_coupling_constant  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                              84.8076
                              2                             -11.2570
                              3                             -11.2548
                              4                             -11.2543
                 2            0                              84.8074

                                            atom_index_x atom_0       x_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                        1      H  0.002150
                              2                        1      H  0.002150
                              3                        1      H  0.002150
                              4                        1      H  0.002150
                 2            0                        2      H  1.011731

                                                 y_0       z_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0            -0.006031  0.001976
                              2            -0.006031  0.001976
                              3            -0.006031  0.001976
                              4            -0.006031  0.001976
                 2            0             1.463751  0.000277

                                            electronegativity_x  radius_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                             2.2      0.43
                              2                             2.2      0.43
                              3                             2.2      0.43
                              4                             2.2      0.43
                 2            0                             2.2      0.43

                                            n_bonds_x  bond_lengths_mean_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                     1             1.091953
                              2                     1             1.091953
                              3                     1             1.091953
                              4                     1             1.091953
                 2            0                     1             1.091952

                                            bond_lengths_std_x  atom_index_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                            0.0             0
                              2                            0.0             2
                              3                            0.0             3
                              4                            0.0             4
                 2            0                            0.0             0

                                           atom_1       x_1       y_1  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 C -0.012698  1.085804
                              2                 H  1.011731  1.463751
                              3                 H -0.540815  1.447527
                              4                 H -0.523814  1.437933
                 2            0                 C -0.012698  1.085804

                                                 z_1  electronegativity_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.008001                 2.55
                              2             0.000277                 2.20
                              3            -0.876644                 2.20
                              4             0.906397                 2.20
                 2            0             0.008001                 2.55

                                            radius_y  n_bonds_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 0.82          4
                              2                 0.43          1
                              3                 0.43          1
                              4                 0.43          1
                 2            0                 0.82          4

                                            bond_lengths_mean_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                        1.091950
                              2                        1.091952
                              3                        1.091946
                              4                        1.091948
                 2            0                        1.091950

                                            bond_lengths_std_y      dist  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                       0.000003  1.091953
                              2                       0.000000  1.783120
                              3                       0.000000  1.783147
                              4                       0.000000  1.783157
                 2            0                       0.000003  1.091952

                                              dist_x    dist_y    dist_z  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.000220  1.192105  0.000036
                              2             1.019253  2.160261  0.000003
                              3             0.294812  2.112831  0.771973
                              4             0.276638  2.085032  0.817978
                 2            0             1.049455  0.142844  0.000060

                                           type_0
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 1
                              2                 2
                              3                 2
                              4                 2
                 2            0                 1

In [37]:
dataset.test.head()

                                                 id  type  atom_index_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0             4658147  2JHC             2
                              1             4658148  1JHC             2
                              3             4658149  3JHH             2
                 3            0             4658150  1JHC             3
                              1             4658151  2JHC             3

                                           atom_0       x_0  y_0  z_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                 H -1.661639  0.0  1.0
                              1                 H -1.661639  0.0  1.0
                              3                 H -1.661639  0.0  1.0
                 3            0                 H  1.661639  0.0  1.0
                              1                 H  1.661639  0.0  1.0

                                            electronegativity_x  radius_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                             2.2      0.43
                              1                             2.2      0.43
                              3                             2.2      0.43
                 3            0                             2.2      0.43
                              1                             2.2      0.43

                                            n_bonds_x  bond_lengths_mean_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                     1             1.062099
                              1                     1             1.062099
                              3                     1             1.062099
                 3            0                     1             1.062099
                              1                     1             1.062099

                                            bond_lengths_std_x  atom_index_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                            0.0             0
                              1                            0.0             1
                              3                            0.0             3
                 3            0                            0.0             0
                              1                            0.0             1

                                           atom_1       x_1  y_1  z_1  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                 C  0.599539  0.0  1.0
                              1                 C -0.599539  0.0  1.0
                              3                 H  1.661639  0.0  1.0
                 3            0                 C  0.599539  0.0  1.0
                              1                 C -0.599539  0.0  1.0

                                            electronegativity_y  radius_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                            2.55      0.82
                              1                            2.55      0.82
                              3                            2.20      0.43
                 3            0                            2.55      0.82
                              1                            2.55      0.82

                                            n_bonds_y  bond_lengths_mean_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                     2             1.130589
                              1                     2             1.130589
                              3                     1             1.062099
                 3            0                     2             1.130589
                              1                     2             1.130589

                                            bond_lengths_std_y      dist  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                        0.06849  2.261178
                              1                        0.06849  1.062099
                              3                        0.00000  3.323277
                 3            0                        0.06849  1.062099
                              1                        0.06849  2.261178

                                               dist_x  dist_y  dist_z type_0
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0              5.112926     0.0     0.0      2
                              1              1.128054     0.0     0.0      1
                              3             11.044171     0.0     0.0      3
                 3            0              1.128054     0.0     0.0      1
                              1              5.112926     0.0     0.0      2

In [39]:
dataset.dipole_moments.head()

                       X    Y       Z
molecule_name
dsgdb9nsd_000001  0.0000  0.0  0.0000
dsgdb9nsd_000002 -0.0002  0.0  1.6256
dsgdb9nsd_000003  0.0000  0.0 -1.8511
dsgdb9nsd_000005  0.0000  0.0 -2.8937
dsgdb9nsd_000007  0.0000  0.0  0.0000

In [40]:
dataset.magnetic_shielding_tensors.head()

,atom_index,XX,YX,ZX,XY,YY,ZY,XZ,YZ,ZZ
molecule_name,,,,,,,,,,
dsgdb9nsd_000001,0,195.3150,0.0000,-0.0001,0.0000,195.3170,0.0007,-0.0001,0.0007,195.3170
dsgdb9nsd_000001,1,31.3410,-1.2317,4.0544,-1.2317,28.9546,-1.7173,4.0546,-1.7173,34.0861
dsgdb9nsd_000001,2,31.5814,1.2173,-4.1474,1.2173,28.9036,-1.6036,-4.1476,-1.6036,33.8967
dsgdb9nsd_000001,3,31.5172,4.1086,1.2723,4.1088,33.9068,1.6950,1.2724,1.6951,28.9579
dsgdb9nsd_000001,4,31.4029,-4.0942,-1.1793,-4.0944,34.0776,1.6259,-1.1795,1.6260,28.9013

In [41]:
dataset.mulliken_charges.head()

                  atom_index  mulliken_charge
molecule_name
dsgdb9nsd_000001           0        -0.535689
dsgdb9nsd_000001           1         0.133921
dsgdb9nsd_000001           2         0.133922
dsgdb9nsd_000001           3         0.133923
dsgdb9nsd_000001           4         0.133923

In [42]:
dataset.potential_energy.head()

                  potential_energy
molecule_name
dsgdb9nsd_000001         -40.52368
dsgdb9nsd_000002         -56.56025
dsgdb9nsd_000003         -76.42608
dsgdb9nsd_000005         -93.42849
dsgdb9nsd_000007         -79.83869

In [43]:
dataset.scalar_coupling_contributions.head()

                                            type       fc        sd      pso  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             1JHC  83.0224  0.254579  1.25862
                              2             2JHH -11.0347  0.352978  2.85839
                              3             2JHH -11.0325  0.352944  2.85852
                              4             2JHH -11.0319  0.352934  2.85855
                 2            0             1JHC  83.0222  0.254585  1.25861

                                                 dso
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.272010
                              2            -3.433600
                              3            -3.433870
                              4            -3.433930
                 2            0             0.272013

In [44]:
dataset.structures.head()

,atom_index,atom,x,y,z,electronegativity,radius,n_bonds,bond_lengths_mean,bond_lengths_std
molecule_name,,,,,,,,,,
dsgdb9nsd_000001,0,C,-0.012698,1.085804,0.008001,2.55,0.82,4,1.091950,0.000003
dsgdb9nsd_000001,1,H,0.002150,-0.006031,0.001976,2.20,0.43,1,1.091953,0.000000
dsgdb9nsd_000001,2,H,1.011731,1.463751,0.000277,2.20,0.43,1,1.091952,0.000000
dsgdb9nsd_000001,3,H,-0.540815,1.447527,-0.876644,2.20,0.43,1,1.091946,0.000000
dsgdb9nsd_000001,4,H,-0.523814,1.437933,0.906397,2.20,0.43,1,1.091948,0.000000

- index = ['molecule_name', 'atom_index_0', 'atom_index_1']
    - train
    - test
    - scalar_coupling_contributions

- index = ['molecule_name', 'atom_index']
    - magnetic_shielding_tensors
    - mulliken_charges
    - structures

- index = ['molecule_name']
    - dipole_moments
    - potential_energy