# Setup

In [1]:
# enable to reimport modules
%load_ext autoreload
%autoreload 2

In [2]:
import warnings

import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_columns = 999

In [3]:
warnings.filterwarnings('ignore')

# Usable Features List

In [4]:
from scripts.feature import FeatureFactory
for lst in FeatureFactory().feature_list():
    print(f'"{lst}",')

"MoleculeType",
"MoleculeType0",
"Atom0",
"Atom1",
"AtomX0",
"AtomX1",
"AtomY0",
"AtomY1",
"AtomZ0",
"AtomZ1",
"MoleculeDistance",
"MoleculeDistanceX",
"MoleculeDistanceY",
"MoleculeDistanceZ",
"MoleculeCount",
"MoleculeX0Statistics",
"MoleculeX1Statistics",
"MoleculeY0Statistics",
"MoleculeY1Statistics",
"MoleculeZ0Statistics",
"MoleculeZ1Statistics",
"MoleculeDistanceStatistics",
"MoleculeDistanceXStatistics",
"MoleculeDistanceYStatistics",
"MoleculeDistanceZStatistics",
"Atom0Count",
"Atom1Count",
"Atom0X1Statistics",
"Atom1X0Statistics",
"Atom0Y1Statistics",
"Atom1Y0Statistics",
"Atom0Z1Statistics",
"Atom1Z0Statistics",
"Atom0DistanceStatistics",
"Atom1DistanceStatistics",
"Atom0DistanceXStatistics",
"Atom1DistanceXStatistics",
"Atom0DistanceYStatistics",
"Atom1DistanceYStatistics",
"Atom0DistanceZStatistics",
"Atom1DistanceZStatistics",
"TypeX0Statistics",
"TypeX1Statistics",
"TypeY0Statistics",
"TypeY1Statistics",
"TypeZ0Statistics",
"TypeZ1Statistics",
"TypeDistanceStatistics",
"TypeDistanceXStatistics",
"TypeDistanceYStatistics",
"TypeDistanceZStatistics",
"FermiContact",
"SpinDipolar",
"ParaMagneticSpinOrbit",
"DiamagneticSpinOrbit",

# Experiment

In [8]:
from scripts.experiment import Experiment
ex = Experiment()
# ex = Experiment(dataset, X_train,  y_train, X_test)
y_pred = ex.run(nrows=None)
dataset = ex.dataset_
X_train = ex.X_train_
y_train = ex.y_train_
X_test = ex.X_test_

Target: sd

  0%|          | 0/5 [00:00<?, ?it/s]
 20%|██        | 1/5 [00:11<00:45, 11.42s/it]
 40%|████      | 2/5 [00:17<00:29,  9.73s/it]
 60%|██████    | 3/5 [00:22<00:16,  8.36s/it]
 80%|████████  | 4/5 [00:27<00:07,  7.43s/it]
100%|██████████| 5/5 [00:33<00:00,  6.96s/it]
  0%|          | 0/5 [00:00<?, ?it/s]
 20%|██        | 1/5 [00:04<00:19,  4.80s/it]
 40%|████      | 2/5 [00:07<00:12,  4.12s/it]
 60%|██████    | 3/5 [00:09<00:07,  3.65s/it]
 80%|████████  | 4/5 [00:12<00:03,  3.30s/it]
100%|██████████| 5/5 [00:14<00:00,  3.06s/it]

Not found the best parameters
Training until validation scores don't improve for 3 rounds.
Did not meet early stopping. Best iteration is:
[100]	valid_0's l2: 0.00327019
Training until validation scores don't improve for 3 rounds.
Did not meet early stopping. Best iteration is:
[100]	valid_0's l2: 0.00327439
Score: -3.6572538605920206

TypeError: Index(...) must be called with a collection of some kind, 'sd' was passed

# Show the Dataframes

In [43]:
X_train.head()

                                            molecule_couples  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                           10
                              2                           10
                              3                           10
                              4                           10
                 2            1                           10

                                            molecule_dist_mean  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                       1.506668
                              2                       1.506668
                              3                       1.506668
                              4                       1.506668
                 2            1                       1.506668

                                            molecule_dist_min  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                      1.091946
                              2                      1.091946
                              3                      1.091946
                              4                      1.091946
                 2            1                      1.091946

                                            molecule_dist_max  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                      1.783158
                              2                      1.783158
                              3                      1.783158
                              4                      1.783158
                 2            1                      1.783158

                                            atom_0_couples_count  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                                4
                              2                                3
                              3                                2
                              4                                1
                 2            1                                4

                                            atom_1_couples_count
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000001 0            1                                4
                              2                                4
                              3                                4
                              4                                4
                 2            1                                1

In [44]:
y_train.head()

                                            type       fc
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             1JHC  83.0224
                              2             2JHH -11.0347
                              3             2JHH -11.0325
                              4             2JHH -11.0319
                 2            0             1JHC  83.0222

In [45]:
X_test.head()

                                            molecule_couples  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                            5
                              3                            5
                 1            2                            5
                              3                            5
                 3            2                            5

                                            molecule_dist_mean  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                       1.993966
                              3                       1.993966
                 1            2                       1.993966
                              3                       1.993966
                 3            2                       1.993966

                                            molecule_dist_min  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                      1.062099
                              3                      1.062099
                 1            2                      1.062099
                              3                      1.062099
                 3            2                      1.062099

                                            molecule_dist_max  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                      3.323277
                              3                      3.323277
                 1            2                      3.323277
                              3                      3.323277
                 3            2                      3.323277

                                            atom_0_couples_count  \
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                                3
                              3                                2
                 1            2                                3
                              3                                2
                 3            2                                3

                                            atom_1_couples_count
molecule_name    atom_index_1 atom_index_0
dsgdb9nsd_000004 0            2                                2
                              3                                2
                 1            2                                2
                              3                                2
                 3            2                                1

In [92]:
dataset.train.head(10)

                                            id  type  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0              0  1JHC
                              2              1  2JHH
                              3              2  2JHH
                              4              3  2JHH
                 2            0              4  1JHC
                              3              5  2JHH
                              4              6  2JHH
                 3            0              7  1JHC
                              4              8  2JHH
                 4            0              9  1JHC

                                            scalar_coupling_constant atom_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                              84.8076      H
                              2                             -11.2570      H
                              3                             -11.2548      H
                              4                             -11.2543      H
                 2            0                              84.8074      H
                              3                             -11.2541      H
                              4                             -11.2548      H
                 3            0                              84.8093      H
                              4                             -11.2543      H
                 4            0                              84.8095      H

                                                 x_0       y_0       z_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.002150 -0.006031  0.001976
                              2             0.002150 -0.006031  0.001976
                              3             0.002150 -0.006031  0.001976
                              4             0.002150 -0.006031  0.001976
                 2            0             1.011731  1.463751  0.000277
                              3             1.011731  1.463751  0.000277
                              4             1.011731  1.463751  0.000277
                 3            0            -0.540815  1.447527 -0.876644
                              4            -0.540815  1.447527 -0.876644
                 4            0            -0.523814  1.437933  0.906397

                                           atom_1       x_1       y_1  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0                 C -0.012698  1.085804
                              2                 H  1.011731  1.463751
                              3                 H -0.540815  1.447527
                              4                 H -0.523814  1.437933
                 2            0                 C -0.012698  1.085804
                              3                 H -0.540815  1.447527
                              4                 H -0.523814  1.437933
                 3            0                 C -0.012698  1.085804
                              4                 H -0.523814  1.437933
                 4            0                 C -0.012698  1.085804

                                                 z_1      dist    dist_x  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.008001  1.091953  0.000220
                              2             0.000277  1.783120  1.019253
                              3            -0.876644  1.783147  0.294812
                              4             0.906397  1.783157  0.276638
                 2            0             0.008001  1.091952  1.049455
                              3            -0.876644  1.783158  2.410399
                              4             0.906397  1.783148  2.357897
                 3            0             0.008001  1.091946  0.278907
                              4             0.906397  1.783148  0.000289
                 4            0             0.008001  1.091948  0.261239

                                              dist_y    dist_z type_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             1.192105  0.000036      1
                              2             2.160261  0.000003      2
                              3             2.112831  0.771973      2
                              4             2.085032  0.817978      2
                 2            0             0.142844  0.000060      1
                              3             0.000263  0.768989      2
                              4             0.000667  0.821055      2
                 3            0             0.130843  0.782596      1
                              4             0.000092  3.179235      2
                 4            0             0.123994  0.807116      1

                                                 fc        sd      pso  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             83.0224  0.254579  1.25862
                              2            -11.0347  0.352978  2.85839
                              3            -11.0325  0.352944  2.85852
                              4            -11.0319  0.352934  2.85855
                 2            0             83.0222  0.254585  1.25861
                              3            -11.0317  0.352932  2.85856
                              4            -11.0324  0.352943  2.85853
                 3            0             83.0241  0.254634  1.25856
                              4            -11.0319  0.352943  2.85856
                 4            0             83.0243  0.254628  1.25856

                                                 dso
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             0.272010
                              2            -3.433600
                              3            -3.433870
                              4            -3.433930
                 2            0             0.272013
                              3            -3.433950
                              4            -3.433870
                 3            0             0.272012
                              4            -3.433930
                 4            0             0.272012

In [42]:
dataset.test.head()

                                                 id  type atom_0       x_0  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0             4658147  2JHC      H -1.661639
                              1             4658148  1JHC      H -1.661639
                              3             4658149  3JHH      H -1.661639
                 3            0             4658150  1JHC      H  1.661639
                              1             4658151  2JHC      H  1.661639

                                            y_0  z_0 atom_1       x_1  y_1  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0             0.0  1.0      C  0.599539  0.0
                              1             0.0  1.0      C -0.599539  0.0
                              3             0.0  1.0      H  1.661639  0.0
                 3            0             0.0  1.0      C  0.599539  0.0
                              1             0.0  1.0      C -0.599539  0.0

                                            z_1      dist     dist_x  dist_y  \
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0             1.0  2.261178   5.112926     0.0
                              1             1.0  1.062099   1.128054     0.0
                              3             1.0  3.323277  11.044171     0.0
                 3            0             1.0  1.062099   1.128054     0.0
                              1             1.0  2.261178   5.112926     0.0

                                            dist_z type_0
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000004 2            0                0.0      2
                              1                0.0      1
                              3                0.0      3
                 3            0                0.0      1
                              1                0.0      2

In [11]:
dataset.dipole_moments.head()

AttributeError: 'Dataset' object has no attribute 'dipole_moments'

In [ ]:
dataset.magnetic_shielding_tensors.head()

In [ ]:
dataset.mulliken_charges.head()

In [ ]:
dataset.potential_energy.head()

In [ ]:
dataset.scalar_coupling_contributions.head()

In [12]:
dataset.structures.head()

,atom_index,atom,x,y,z,electronegativity,radius,n_bonds,bond_lengths_mean,bond_lengths_std
molecule_name,,,,,,,,,,
dsgdb9nsd_000001,0,C,-0.012698,1.085804,0.008001,2.55,0.82,4,1.091950,0.000003
dsgdb9nsd_000001,1,H,0.002150,-0.006031,0.001976,2.20,0.43,1,1.091953,0.000000
dsgdb9nsd_000001,2,H,1.011731,1.463751,0.000277,2.20,0.43,1,1.091952,0.000000
dsgdb9nsd_000001,3,H,-0.540815,1.447527,-0.876644,2.20,0.43,1,1.091946,0.000000
dsgdb9nsd_000001,4,H,-0.523814,1.437933,0.906397,2.20,0.43,1,1.091948,0.000000

- index = ['molecule_name', 'atom_index_0', 'atom_index_1']
    - train
    - test
    - scalar_coupling_contributions

- index = ['molecule_name', 'atom_index']
    - magnetic_shielding_tensors
    - mulliken_charges
    - structures

- index = ['molecule_name']
    - dipole_moments
    - potential_energy