# Setup

In [1]:
# enable to reimport modules
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_columns = 999

In [3]:
from scripts.feature import FeatureFactory
ff = FeatureFactory()
ff.feature_list()

['MoleculeCount', 'MoleculeDistanceStatistics', 'Atom0Count', 'Atom1Count']

In [41]:
from scripts.experiment import Experiment
ex = Experiment()
y_pred = ex.run()

[autoreload of scripts.model failed: Traceback (most recent call last):
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 265, in update_function
    setattr(old, name, getattr(new, name))
ValueError: predict() requires a code object with 0 free vars, not 1
]

load the dataset pickle

 50%|█████     | 2/4 [00:00<00:00,  7.94it/s]Exception during reset or similar
Traceback (most recent call last):
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 739, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 671, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 856, in _reset
    self._reset_agent.rollback()
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1705, in rollback
    self._do_rollback()
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1743, in _do_rollback
    self.connection._rollback_impl()
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 741, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 739, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/shohei_goda/.pyenv/versions/3.7.1/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/f405)
100%|██████████| 4/4 [00:18<00:00,  4.90s/it]
100%|██████████| 4/4 [00:10<00:00,  2.62s/it]
/Users/shohei_goda/Desktop/shohei/kaggle/CHAMPS/notebooks/scripts/dataproc.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

not found best parameters

RecursionError: maximum recursion depth exceeded while calling a Python object

In [31]:
X_train.head(1)

,,,id,molecule_dist_mean,molecule_dist_min,molecule_dist_max,atom_0_couples_count,atom_1_couples_count
molecule_name,atom_index_1,atom_index_0,,,,,,
dsgdb9nsd_000001,0,1,10,1.506668,1.091946,1.783158,4,4

In [33]:
y_train.head(1)

                                                 fc  type
molecule_name    atom_index_0 atom_index_1
dsgdb9nsd_000001 1            0             83.0224  1JHC

In [35]:
X_test.head(1)

,,,id,molecule_dist_mean,molecule_dist_min,molecule_dist_max,atom_0_couples_count,atom_1_couples_count
molecule_name,atom_index_1,atom_index_0,,,,,,
dsgdb9nsd_000004,0,2,5,1.993966,1.062099,3.323277,3,2

In [36]:
dataset.train.head(1)

,,,id,type,scalar_coupling_constant,atom_index_x,atom_0,x_0,y_0,z_0,electronegativity_x,radius_x,n_bonds_x,bond_lengths_mean_x,bond_lengths_std_x,atom_index_y,atom_1,x_1,y_1,z_1,electronegativity_y,radius_y,n_bonds_y,bond_lengths_mean_y,bond_lengths_std_y,dist,dist_x,dist_y,dist_z,type_0
molecule_name,atom_index_0,atom_index_1,,,,,,,,,,,,,,,,,,,,,,,,,,,,
dsgdb9nsd_000001,1,0,0,1JHC,84.8076,1,H,0.00215,-0.006031,0.001976,2.2,0.43,1,1.091953,0.0,0,C,-0.012698,1.085804,0.008001,2.55,0.82,4,1.09195,0.000003,1.091953,0.00022,1.192105,0.000036,1

In [45]:
dataset.test.head(1)

,,,id,type,atom_index_x,atom_0,x_0,y_0,z_0,electronegativity_x,radius_x,bond_lengths_mean_x,...,atom_index_y,atom_1,x_1,y_1,z_1,electronegativity_y,radius_y,bond_lengths_mean_y,bond_lengths_std_y,n_bonds_y
molecule_name,atom_index_0,atom_index_1,,,,,,,,,,,,,,,,,,,,,
dsgdb9nsd_000004,2,0,4658147,2JHC,2,H,-1.661639,0.0,1.0,2.2,0.43,1.062099,...,0,C,0.599539,0.0,1.0,2.55,0.82,1.130589,0.06849,2

In [37]:
dataset.submission.head(1)

        id  scalar_coupling_constant
0  4658147                         0

In [46]:
dataset.dipole_moments.head(1)

                    X    Y    Z
molecule_name
dsgdb9nsd_000001  0.0  0.0  0.0

In [47]:
dataset.magnetic_shielding_tensors.head(1)

,atom_index,XX,YX,ZX,XY,YY,ZY,XZ,YZ,ZZ
molecule_name,,,,,,,,,,
dsgdb9nsd_000001,0,195.315,0.0,-0.0001,0.0,195.317,0.0007,-0.0001,0.0007,195.317

In [48]:
dataset.mulliken_charges.head(1)

                  atom_index  mulliken_charge
molecule_name
dsgdb9nsd_000001           0        -0.535689

In [49]:
dataset.potential_energy.head(1)

                  potential_energy
molecule_name
dsgdb9nsd_000001         -40.52368

In [26]:
dataset.scalar_coupling_contributions.head(1)

,,,type,fc,sd,pso,dso
molecule_name,atom_index_0,atom_index_1,,,,,
dsgdb9nsd_000001,1,0,1JHC,83.0224,0.254579,1.25862,0.27201

In [51]:
dataset.structures.head(1)

,atom_index,atom,x,y,z,electronegativity,radius,bond_lengths_mean,bond_lengths_std,n_bonds
molecule_name,,,,,,,,,,
dsgdb9nsd_000001,0,C,-0.012698,1.085804,0.008001,2.55,0.82,1.09195,0.000003,4